version: '3.7'
services:
  socketio:
    build: .
    command: npm start
    restart: always
    ports:
      - ${EXPOSED_PORT}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - "./data:/usr/src/app/data"